---
- name: package installation
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: false
  tasks:
    - name: yum update
      yum:
        name: "*"
        state: latest

    - name: httpd package installation
      yum:
        name: httpd
        state: present

    - name: starting httpd services
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Install Amazon Linux Extras repository
      yum:
        name: amazon-linux-extras
        state: present

    - name: Enable PHP 8.0
      command: amazon-linux-extras enable php8.0
      args:
        creates: /etc/amazon-linux-extras-enabled.d/php8.0

    - name: Install PHP 8 and common extensions
      yum:
        name:
          - php
          - php-cli
          - php-sodium
          - php-dom
          - php-pear
          - php-gettext
          - php-bcmath
          - php-common
          - php-fpm
          - php-json
          - php-mbstring
          - php-mysqlnd
          - php-mysql
          # - php-mcrypt
          - php-xml
          - php-zip
          # - php-imap
          - php-soap
          - php-gd
          - php-curl
          - php-ldap
          - php-fileinfo
        state: present

    - name: Start and enable php-fpm service
      service:
        name: php-fpm
        state: started
        enabled: yes

    - name: Mysql Installation
      become: true
      shell: |
         a=uisdhnfuiewFEwohsdEW 
         d=DATUM
         rpm -Uvh http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm 
         sudo rpm -ivh mysql-community-release-el7-5.noarch.rpm
         yum install mysql mysql-server -y
         systemctl start mysqld
         systemctl enable mysqld
         echo "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('$a');" > reset_pass.sql
         mysql -u root < reset_pass.sql
         echo "Database creation"
         mysql --host localhost -uroot -p${a} -e "CREATE DATABASE $d;"

      register: SEQOUT

    - debug: msg={{SEQOUT.stdout_lines}}

    - name: Web Installation
      become: true
      shell: |
        #  cd /var/www/html
        #  wget SOURCELINK
        #  unzip * && rm -rf *dl=0
        #  mv -v * .. && cd ..
        #  rm -rf html && mv -v gofer* html 
         
        #  cd /var/www/html && > .env
        #  cat << EOF >> .env
        #  DB_HOST=127.0.0.1
        #  DB_DATABASE=DATUM
        #  DB_USERNAME=root
        #  DB_PASSWORD=uisdhnfuiewFEwohsdEW
        #  APP_ENV=local
        #  APP_DEBUG=true
        #  FIREBASE_PREFIX=Demo
        #  APP_LOG_LEVEL=debug
        #  SESSION_DRIIVER=file
        #  JWT_SECRET=rpostx94CbCDVyLfuEpqaqVrDceelHh6o4Qy4kmBQ18nrQmIWZsLwU31XFOAZq9k
        #  EOF
         
        #  touch /var/www/html/public/.htaccess
        #  cat << EOF >> /var/www/html/public/.htaccess
        #  <IfModule mod_rewrite.c>
        #  <IfModule mod_negotiation.c>
        #  Options -MultiViews -Indexes
        #  </IfModule>

        #  RewriteEngine On

        #  # Handle Authorization Header
        #  RewriteCond %{HTTP:Authorization} .
        #  RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

        #  # Redirect Trailing Slashes If Not A Folder...
        #  RewriteCond %{REQUEST_FILENAME} !-d
        #  RewriteCond %{REQUEST_URI} (.+)/$
        #  RewriteRule ^ %1 [L,R=301]

        #  # Handle Front Controller...
        #  RewriteCond %{REQUEST_FILENAME} !-d
        #  RewriteCond %{REQUEST_FILENAME} !-f
        #  RewriteRule ^ index.php [L]
        #  </IfModule>
        #  EOF

        #  cd /var/www/html
        #  mkdir /var/www/html/storage/logs
        #  touch /var/www/html/storage/logs/laravel.log
        #  touch /var/www/html/storage/installed
        #  rm -rvf /var/www/html/public/storage

        #  chmod -Rf 777 /var/www/html/storage
        #  chmod -Rf 777 /var/www/html/bootstrap/cache
        #  chmod -R 777 /var/www/html

        #  php artisan migrate:fresh --path=/database/migrations/* --seed
        #  php artisan storage:link

         cat << EOF >> /etc/httpd/conf/httpd.conf
         <VirtualHost *:80>
         ServerName 3.210.194.149
         DocumentRoot /var/www/html/
         <Directory /var/www/html/>
         Options Indexes FollowSymLinks MultiViews
         AllowOverride All
         Order allow,deny
         allow from all
         </Directory>
         </VirtualHost>
         EOF
         service httpd restart
    
      register: SEQOUT

    - debug: msg={{SEQOUT.stdout_lines}}
...
