---
- name: package installation
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: false
  tasks:
    - name: httpd package installation
      yum:
        name: httpd
        state: present
    - name: starting httpd services
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Php Installation
      become: true
      shell: |
         sed -i -e '/enabled/s/1/0/' /etc/yum/pluginconf.d/priorities.conf
         yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
         yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y
         yum-config-manager --enable remi-php73
         yum install php php-sodium php-mbstring php-dom php-pear php-gettext php-bcmath php-json php-xml php-zip php-imap php-mysqlnd php-soap php-mcrypt php-cli php-gd php-curl php-mysql php-ldap php-zip php-fileinfo -y
         php -v
   
      register: SEQOUT

    - debug: msg={{SEQOUT.stdout_lines}}
    
    - name: Mysql Installation
      become: true
      shell: |
         a=uisdhnfuiewFEwohsdEW 
         d=DATUM
         rpm -Uvh http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm 
         sudo rpm -ivh mysql-community-release-el7-5.noarch.rpm
         yum install mysql mysql-server -y
         systemctl start mysqld
         systemctl enable mysqld
         echo "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('$a');" > reset_pass.sql
         mysql -u root < reset_pass.sql
         echo "Database creation"
         mysql --host localhost -uroot -p${a} -e "CREATE DATABASE $d;"

      register: SEQOUT

    - debug: msg={{SEQOUT.stdout_lines}}

    - name: Web Installation
      become: true
      shell: |
         cd /var/www/html
         wget SOURCELINK
         unzip * && rm -rf *dl=0
         mv -v * .. && cd ..
         rm -rf html && mv -v gofer* html 
         
         cd /var/www/html && > .env
         cat << EOF >> .env
         DB_HOST=127.0.0.1
         DB_DATABASE=DATUM
         DB_USERNAME=root
         DB_PASSWORD=uisdhnfuiewFEwohsdEW
         APP_ENV=local
         APP_DEBUG=true
         FIREBASE_PREFIX=Demo
         APP_LOG_LEVEL=debug
         SESSION_DRIIVER=file
         JWT_SECRET=rpostx94CbCDVyLfuEpqaqVrDceelHh6o4Qy4kmBQ18nrQmIWZsLwU31XFOAZq9k
         EOF
         
         touch /var/www/html/public/.htaccess
         cat << EOF >> /var/www/html/public/.htaccess
         <IfModule mod_rewrite.c>
         <IfModule mod_negotiation.c>
         Options -MultiViews -Indexes
         </IfModule>

         RewriteEngine On

         # Handle Authorization Header
         RewriteCond %{HTTP:Authorization} .
         RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

         # Redirect Trailing Slashes If Not A Folder...
         RewriteCond %{REQUEST_FILENAME} !-d
         RewriteCond %{REQUEST_URI} (.+)/$
         RewriteRule ^ %1 [L,R=301]

         # Handle Front Controller...
         RewriteCond %{REQUEST_FILENAME} !-d
         RewriteCond %{REQUEST_FILENAME} !-f
         RewriteRule ^ index.php [L]
         </IfModule>
         EOF

         cd /var/www/html
         mkdir /var/www/html/storage/logs
         touch /var/www/html/storage/logs/laravel.log
         touch /var/www/html/storage/installed
         rm -rvf /var/www/html/public/storage

         chmod -Rf 777 /var/www/html/storage
         chmod -Rf 777 /var/www/html/bootstrap/cache
         chmod -R 777 /var/www/html

         php artisan migrate:fresh --path=/database/migrations/* --seed
         php artisan storage:link

         cat << EOF >> /etc/httpd/conf/httpd.conf
         <VirtualHost *:80>
         ServerName IPADRESS
         DocumentRoot /var/www/html/public
         <Directory /var/www/html/public>
         Options Indexes FollowSymLinks MultiViews
         AllowOverride All
         Order allow,deny
         allow from all
         </Directory>
         </VirtualHost>
         EOF
         service httpd restart
    
      register: SEQOUT

    - debug: msg={{SEQOUT.stdout_lines}}
...
